config/routes.rb
Forem::Application.routes.draw do
  mount Forem::Engine, :at => "/"
	root :to => "forem/forums#index"

	devise_for :users, :class_name => "Forem::User" do
  	get "sign_in", :to => "devise/sessions#new"
  end

	match 'users/:id', :to => "users#show", :as => :user

end

app/models/forem/user.rb
module Forem
  class User < ActiveRecord::Base
  	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  	# Setup accessible (or protected) attributes for your model
  	attr_accessible :email, :password, :password_confirmation, :forem_admin, :name

  	def to_s
  		self.name
  	end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def forem_user
    current_user
  end
  helper_method :forem_user

  protect_from_forgery
end

app/controllers/forem/home_controller.rb
module Forem
  class HomeController < ApplicationController
    def index
    end
  
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forem/home_helper.rb
module Forem
  module HomeHelper
  end
end

app/helpers/forem/posts_helper.rb
module Forem
  module PostsHelper
    def avatar(user, options = {})
      if (email = user.try(:email)).present?
        image_tag('rails.png') #avatar_url(email, options), :alt => "Gravatar")
      end
    end

    def avatar_url(email, options = {})
      require 'digest/md5' unless defined?(Digest::MD5)
      md5 = Digest::MD5.hexdigest(email.to_s.strip.downcase)

      options[:s] = options.delete(:size) || 60
      options[:d] = options.delete(:default) || default_gravatar
      options.delete(:d) unless options[:d]
      "http://www.gravatar.com/avatar/#{md5}?#{options.to_param}"
    end

    def default_gravatar
      image = Forem.default_gravatar_image

      case
      when image && URI(image).absolute?
        image
      when image
        request.protocol +
          request.host_with_port +
          path_to_image(image)
      else
        Forem.default_gravatar
      end
    end
  end
end

app/helpers/forem/topics_helper.rb
#encoding: utf-8
module Forem
  module TopicsHelper
    def link_to_latest_post(post)
      text = "последнее обновление #{post.created_at.strftime("%d.%m.%y %H:%M")} #{post.user}" #"#{time_ago_in_words(post.created_at)} #{t("ago_by")} #{post.user}"
      link_to text, forum_topic_path(post.topic.forum, post.topic, :anchor => "post-#{post.id}")
    end
  end
end

app/views/forem/admin/base/index.html.erb
<h1><%= t('forem.admin.area') %></h1>

<p>
  <%= t('forem.admin.welcome') %>
</p>

<ul>
  <li><%= link_to t('forem.admin.forum.index'), admin_forums_path %> </li>
  <li><%= link_to t('forem.admin.category.index'), admin_categories_path %></li>
</ul>

app/views/forem/admin/categories/_form.html.erb
<%= simple_form_for [:admin, @category] do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/forem/admin/categories/edit.html.erb
<h2><%= t("forem.category.edit", :title => @category.name) %></h2>

<%= render "form" %>

app/views/forem/admin/categories/index.html.erb
<h2><%= t("forem.admin.category.index") %></h2>

<%= link_to t("forem.admin.category.new_link"), new_admin_category_path %>

<table id='forums' class='forums subdued' cellspacing='0'>
  <thead>
    <tr>
      <th><%= t('edit', :scope => 'forem.admin.categories') %></th>
      <th><%= t('delete', :scope => 'forem.admin.categories') %></th>
      <th><%= t('category', :scope => 'forem.admin.categories') %></th>

    </tr>
  </thead>
  <tbody>
    <% @category.each do |category| %>
      <tr class="forum <%= cycle("odd", "even") %>">
        <td><%= link_to t('edit', :scope => 'forem.admin.categories'), edit_admin_category_path(category) %></td>
        <td><%= link_to t('delete', :scope => 'forem.admin.categories'), admin_category_path(category), :method => :delete, :confirm => t("delete_confirm", :scope => "forem.admin.categories") %></td>
        <td>
          <%= category.name %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('forem.admin.forum.index'), admin_forums_path %>

app/views/forem/admin/categories/new.html.erb
<h2><%= t("forem.category.new") %></h2>

<%= render "form" %>

app/views/forem/admin/forums/_form.html.erb
<%= simple_form_for [:admin, @forum] do |f| %>
  <%= f.association :category, :include_blank => false %>
  <%= f.input :title %>
  <%= f.input :description, :as => :text %>
  
  <%= f.submit %>
<% end %>

app/views/forem/admin/forums/edit.html.erb
<h2><%= t("forem.forum.edit", :title => @forum.title) %></h2>

<%= render "form" %>

app/views/forem/admin/forums/index.html.erb
<h2><%= t("forem.admin.forum.index") %></h2>

<%= link_to t("forem.admin.forum.new_link"), new_admin_forum_path %>

<table id='forums' class='forums subdued' cellspacing='0'>
  <thead>
    <tr>
      <th><%= t('edit', :scope => 'forem.admin.forums') %></th>
      <th><%= t('delete', :scope => 'forem.admin.forums') %></th>
      <th><%= t('forum', :scope => 'forem.admin.forums') %></th>
      <th><%= t('category', :scope => 'forem.admin.forums') %></th>
      <th><%= t('topics', :scope => 'forem.admin.forums') %></th>
      <th><%= t('posts', :scope => 'forem.admin.forums') %></th>      
    </tr>
  </thead>
  <tbody>
    <% @forums.each do |forum| %>
      <tr class="forum <%= cycle("odd", "even") %>">
        <td><%= link_to t('edit', :scope => 'forem.admin.forums'), edit_admin_forum_path(forum) %></td>
        <td><%= link_to t('delete', :scope => 'forem.admin.forums'), admin_forum_path(forum), :method => :delete, :confirm => t("delete_confirm", :scope => "forem.admin.forums") %></td>
        <td>
          <%= link_to forum.title, forum_path(forum) %>
          <div class='description'><%= forum.description %></div>
          <%= t('.last_post') %>
          <% if last_post = forum.posts.last %>
            <%= link_to(last_post.topic, forum_topic_path(forum, last_post.topic)) -%> by <%= last_post.user %> <%= time_ago_in_words(last_post.created_at) -%>
          <% else %>
            <%= t('.none') %>
          <% end %>
        </td>
        <td><%= forum.category.name %></td>
        <td><%= forum.topics.count %></td>
        <td><%= forum.posts.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/forem/admin/forums/new.html.erb
<h2><%= t("forem.forum.new") %></h2>

<%= render "form" %>

app/views/forem/admin/topics/_form.html.erb
<%= simple_form_for [:admin, @topic] do |f| %>
  <%= f.input :subject %>
  <%= f.association :forum , :label => "Forum" %>
  <%= f.label :locked %>
  <%= f.check_box :locked %>
  <%= f.label :pinned %>
  <%= f.check_box :pinned %>
  <%= f.label :hidden %>
  <%= f.check_box :hidden %>

  <br />
  <%= f.submit %>
<% end %>

app/views/forem/admin/topics/edit.html.erb
<h2><%= t("forem.topic.edit", :subject => @topic.subject) %></h2>

<%= render "form" %>

app/views/forem/categories/_category.html.erb
<% if can?(:read, category) %>
  <div class='category' id='category_<%= category.id %>'>
    <h2><%= link_to category.name, category %></h2>
    <%= render "forem/forums/listing", :category => category %>
  </div>
<% end %>

app/views/forem/categories/show.html.erb
<h2><%= link_to t('forem.forum.forums'), forums_path %> &raquo; <%= link_to @category, @category %></h2>
<%= render @category %>

app/views/forem/forums/_forum.html.erb
<% if can?(:read, forum) %>
  <tr class="forum <%= cycle("odd", "even") %>">
    <td>
      <%= link_to forum.title, forum_path(forum), :class => "title" %>
      <div class='description'><%= forum.description %></div>
      <%= t('.last_post') -%>
      <span class='last_post'>
          <% if last_post = forum.last_post_for(forem_user) -%>
            <%= link_to(last_post.topic, forum_topic_path(forum, last_post.topic)) -%> <%= t('by') %> <%= last_post.user %> <%= t('time_ago_in_words', :time => time_ago_in_words(last_post.created_at)) -%>
          <% else %>
            <%= t('.none') -%>
          <% end %>
        </span>
    </td>
    <td><%= forum.topics.count %></td>
    <td><%= forum.posts.count %></td>
    <td><%= forum.views.sum(:count) %></td>
  </tr>
<% end %>

app/views/forem/forums/_head.html.erb
<div id='forum'>
  <h2><%= link_to t('forem.forum.forums'), forums_path %> &raquo; <%= link_to forum.category, forum.category %> &raquo; <%= link_to forum.title, forum %></h2>
  <small><%= forum.description %></small>
  <menu>
    <% unless @topic.try(:new_record?) %>
      <% if can? :create_topic, @forum %>
        <%= link_to t('forem.topic.links.new'), new_forum_topic_path(forum) %>
      <% end %>
    <% end %>
    <% if @topic %>
      <%= link_to t('forem.topic.links.back_to_topics'), forum_path(forum) %>
    <% end %>
  </menu>
</div>

app/views/forem/forums/_listing.html.erb
<table id='forums' class='forums subdued' cellspacing='0'>
  <thead>
  <tr>
    <th><%= t('.forums') %></th>
    <th><%= t('.topics') %></th>
    <th><%= t('.posts') %></th>
    <th><%= t('.views') %></th>
  </tr>
  </thead>
  <tbody>
    <%= render category.forums %>
  </tbody>
</table>

app/views/forem/forums/index.html.erb
<h2><%= t('.title') %></h2>

<%= render @categories %>

<br>
<footer id='admin_link'>
  <% if forem_admin? %>
    <%= link_to t("area", :scope => "forem.admin"), admin_root_path %>
  <% end %>
</footer>

app/views/forem/forums/show.html.erb
<%= render :partial => 'forem/forums/head', :locals => { :forum => @forum } %>

<% if @topics.num_pages > 1 %>
  <div class='pages'>
    <%= t('forem.common.pages') -%>: <%= forem_paginate @topics %>
  </div>
<% end %>
<table class='topics subdued' cellspacing='0'>
  <thead>
    <tr>
      <th></th>
      <th><%= t('forem.topic.headings.topic') -%></th>
      <th><%= t('forem.topic.headings.latest') -%></th>
      <th><%= t('forem.topic.headings.posts') -%></th>
      <th><%= t('forem.topic.headings.views') -%></th>
    </tr>
  </thead>
  <tbody>
    <% if @topics.empty? %>
      <tr><td colspan='5' align='center'><%= t('forem.topic.none') %></td></tr>
    <% end %>
    <%= render @topics %>
  </tbody>
</table>

app/views/forem/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/forem/home/index.html.erb</p>
<%= current_user.email %>

app/views/forem/posts/_form.html.erb
<%= f.input :text %>
<% if params[:reply_to_id] %>
  <%= f.hidden_field :reply_to_id, :value => params[:reply_to_id] %>
<% end %>

app/views/forem/posts/_post.html.erb
<a name='post-<%= post.id %>'></a>
<div id='post_<%= post.id %>' class='post <%= cycle('odd', 'even') -%>'>

  <div class='user'>
    <div class='username'>
      <%= link_to_if Forem.user_profile_links, post.user, [main_app, post.user] %>
    </div>
    <div class='icon'><%= avatar(post.user, :size => 60) %></div>
  </div>

  <div class='contents'>
    <time datetime="<%= post.created_at.to_s(:db) -%>"><%= "#{time_ago_in_words(post.created_at)} #{t("ago")}" %></time>
    <%= forem_format(post.text) %>

    <% if post.reply_to %>
      <span class='in_reply_to'>
        <%= link_to "#{t("forem.post.in_reply_to")} #{post.reply_to.user}", "#post-#{post.reply_to.id}" %>
      </span>
    <% end %>

    <ul class='actions'>
      <% if forem_user %>
        <% if can?(:reply, @topic) %>
          <% if @topic.can_be_replied_to? %>
            <li><%= link_to t('reply', :scope => 'forem.topic'), new_topic_post_path(@topic, :reply_to_id => post.id) %></li>
          <% end %>
          <% if @topic.can_be_replied_to? %>
            <li><%= link_to t('quote', :scope => 'forem.topic'), new_topic_post_path(@topic, :reply_to_id => post.id, :quote => true) %></li>
          <% end %>
        <% end %>
        <% if post.owner_or_admin?(forem_user) %>
          <% if can?(:edit_post, @topic.forum) %>
            <li><%= link_to t('edit', :scope => 'forem.post'), edit_topic_post_path(@topic, post) %></li>
          <% end %>
          <li><%= link_to t('delete', :scope => 'forem.topic'), topic_post_path(@topic, post), :method => :delete, :confirm => t("are_you_sure") %></li>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>

app/views/forem/posts/edit.html.erb
<%= render :partial => 'forem/forums/head', :locals => { :forum => @topic.forum } %>

<h2><%= t("forem.post.edit") %></h2>

<%= simple_form_for [@topic, @post] do |f| %>
  <%= render :partial => "form", :locals => { :f => f } %>
  <%= f.submit t("forem.post.buttons.edit") %>
<% end %>

app/views/forem/posts/new.html.erb
<%= render :partial => 'forem/forums/head', :locals => { :forum => @topic.forum } %>

<h2><%= t("forem.post.new") %></h2>

<%= simple_form_for [@topic, @post] do |f| %>
  <%= render :partial => "form", :locals => { :f => f } %>
  <%= f.submit t("forem.post.buttons.reply") %>
<% end %>

app/views/forem/topics/_form.html.erb
<%= simple_form_for [@forum, @topic] do |f| %>
  <%= f.input :subject %>

  <%= f.simple_fields_for :posts do |post| %>
    <%= render :partial => "forem/posts/form", :locals => { :f => post }%>
  <% end %>
  
  <%= f.submit %>
<% end %>

app/views/forem/topics/_head.html.erb
<h2><%= link_to t('forem.forum.forums'), forums_path %> &raquo; <%= link_to topic.forum.title, topic.forum %> &raquo; <%= topic.subject %></h2>
<% if forem_admin? %>
  <%= link_to t('forem.topic.links.edit'), edit_admin_topic_path(topic) %>
<% end %>

app/views/forem/topics/_topic.html.erb
<tr class="topic <%= cycle('odd', 'even') %> <%= topic.locked? ? 'locked' : 'unlocked' %>">
  <td class='icon'>
    <% if topic.locked? %>
      <span class='lock icon'></span>
    <% end %>
    <% if topic.pinned? %>
      <span class='pin icon'></span>
    <% end %>
    <% if forem_user && view = topic.view_for(forem_user) %>
      <% if topic.posts.where("created_at > ?", view.updated_at).any? %>
        <span class='new_posts icon'>new</span>
      <% end %>
    <% end %>
  </td>
  <td class='byline'>
    <div class='subject'><%= link_to topic.subject, forum_topic_path(@forum, topic) %></div>
    <div class='started-by'><%= t "started_by" %><%= topic.posts.by_created_at.first.user %></div>
  </td>
  <td class='latest-post'>
    <%= link_to_latest_post(topic.posts.by_created_at.last) -%>
  </td>
  <td class='posts-count'><%= topic.posts.count %></td>
  <td class='views-count'><%= topic.views.sum(:count) %></td>
</tr>

app/views/forem/topics/new.html.erb
<%= render :partial => 'forem/forums/head', :locals => { :forum => @topic.forum } %>

<h2><%= t("forem.topic.new") %></h2>

<%= render "form" %>

app/views/forem/topics/show.html.erb
<div id='topic' class='<%= 'un' unless @topic.locked? %>locked'>
  <%= render :partial => 'forem/topics/head', :locals => { :topic => @topic } %>

  <menu>
    <% if @topic.can_be_replied_to? && can?(:reply, @topic) %>
      <%= link_to t(".reply"), new_topic_post_path(@topic) %>
    <% end %>
    <% if @topic.user == forem_user || forem_admin? %>
      <%= link_to t(".delete"), forum_topic_path(@forum, @topic), :method => :delete, :confirm => t("are_you_sure") %>
    <% end %>
  </menu>

  <% if forem_admin? %>
    <%= link_to t(".hide.#{@topic.hidden}"), toggle_hide_admin_topic_path(@topic), :method => :put %> | 
    <%= link_to t(".lock.#{@topic.locked}"), toggle_lock_admin_topic_path(@topic), :method => :put %> |
    <%= link_to t(".pin.#{@topic.pinned}"), toggle_pin_admin_topic_path(@topic), :method => :put %>
  <% end %>
  <%= forem_paginate @posts %>
  <div id='posts'>
    <%= render :partial => "forem/posts/post", :collection => @posts %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Forem</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= stylesheet_link_tag "forem/twist/style" %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
    <nav>
        <% if user_signed_in? %>
            <%= link_to current_user.email, main_app.edit_user_registration_path %>
            | <%= link_to "Sign out", main_app.destroy_user_session_path, :method=>:delete %>
            <% if current_user.forem_admin %>
                | <%= link_to "Administrate", forem.admin_root_url %>
            <% end %>
        <% else %>
            <%= link_to "Sign up", main_app.new_user_registration_path %>
            | <%= link_to "Sign in", main_app.new_user_session_path %>
        <% end %>
    </nav>
</header>
<%= yield %>

</body>
</html>